#ifndef MGEFFCONFIG_H
#define MGEFFCONFIG_H

#define _MGEFF_EFFECTOR
#define _MGEFF_FASTMODE
/* #undef HAVE_MESA_MINIGUI */
/* #undef HAVE_EGL_SUPPORT */
/* #undef HAVE_GLES2_SUPPORT */
#define _MGEFF_FIVEPOINTEDSTAREFFECTOR
#define _MGEFF_ROTATEEFFECTOR
#define _MGEFF_RADARSCANEFFECTOR
#define _MGEFF_CUBICROTATEEFFECTOR
#define _MGEFF_SCROLLEFFECTOR
#define _MGEFF_LEAFWINDOWEFFECTOR
#define _MGEFF_ZOOMEFFECTOR
#define _MGEFF_CENTERSPLITEFFECTOR
#define _MGEFF_FLIPEFFECTOR
#define _MGEFF_ALPHAEFFECTOR
#define _MGEFF_ZIPEFFECTOR
#define _MGEFF_CLEAREFFECTOR
#define _MGEFF_PUSHEFFECTOR
#define _MGEFF_WINDOWANIMATION

#ifdef WIN32
#   define inline __inline
#endif /* WIN32 */

#endif /* MGEFFCONFIG_H */
